# Generated by Django 2.1.3 on 2018-11-16 21:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181116_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interested_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, null=True, size=None),
        ),
    ]
