# Generated by Django 2.1.3 on 2018-11-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181116_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/app/images/default_profile.jpeg', upload_to='static/user/profile_pic/'),
        ),
    ]
